<?php
echo"
	<span id='title_drop'>
		<span id='title_drop_button'></span>
		<span id='title_area'>
			<span id='title_drop_menu'>
				<!-- This will probably be generated by PHP -->
				<span class='title_drop_field' id='printers'>Printer</span>
				<span class='title_drop_field' id='accessories'>Accessory</span>
				<span class='title_drop_field' id='workstations'>Workstation</span>
				<span class='title_drop_field' id='servers'>Server</span>
				<span class='title_drop_field' id='paper'>Paper</span>
			</span>
		</span>
	</span>
";
?>